(intern "swift-error")

(ert-deftest swift-module:check-basic-conversion ()
  (should (eq (swift-int 10) 20))
  (should (< (abs (- 21.0 (swift-float 10.5))) 1e-6))
  (should (swift-bool nil))
  (should (not (swift-bool t))))

(ert-deftest swift-module:check-incorrect-num-of-args ()
  (should-error (swift-int) :type 'wrong-number-of-arguments)
  (should-error (swift-int 10 20) :type 'wrong-number-of-arguments))

(ert-deftest swift-module:check-incorrect-arg-type ()
  (should-error (swift-int "a") :type 'wrong-type-argument)
  (should-error (swift-int 10.5) :type 'wrong-type-argument)
  (should-error (swift-float 10) :type 'wrong-type-argument))

(ert-deftest swift-module:check-exception-on-emacs-side ()
  (should-error (swift-calls-bad-function) :type 'void-function))

(ert-deftest swift-module:check-exception-on-swift-side ()
  (should-error (swift-throws 42) :type 'swift-error)
  (should-error (swift-throws-sometimes 42) :type 'swift-error)
  (should (eq (swift-throws-sometimes 41) 41)))

(ert-deftest swift-module:check-opaquely-converted ()
  (let ((a1 (swift-create-a))
        (a2 (swift-create-a))
        (b1 (swift-create-b))
        (b2 (swift-create-b)))
    (should (eq (swift-get-a-x a1) 42))
    (should (eq (swift-get-a-x a2) 42))
    (should (string-equal (swift-get-a-y a1) "Hello"))
    (should (string-equal (swift-get-a-y a2) "Hello"))
    (swift-set-a-x a1 15)
    (swift-set-a-y a1 "Boom")
    (should-error (swift-set-a-x a1 10.0) :type 'wrong-type-argument)
    (should (eq (swift-get-a-x a1) 15))
    (should-not (eq (swift-get-a-x a1) (swift-get-a-x a2)))
    (should-error (swift-get-b-z "str") :type 'wrong-type-argument)
    (should-error (swift-get-b-z a1) :type 'wrong-type-argument)))
